### ISSUE TITLE
Redesign board for QuinLED-ESP32 Ethernet

### ISSUE THREAD

**Issue by mwolter805** [nkitanov/iaq_board#16]
Hello, 
Thank you for the great project! I built an IAQ-Board and it works well. The only issues experienced are the typical WiFi issues. To help with these WiFi issues I am interested in designing a new PCB to work with the [QuinLED-ESP32](https://quinled.info/quinled-esp32/) boards. Specifically, the [ethernet](https://quinled.info/quinled-esp32-ethernet/) model but it should work for the other QuinLED boards too. Also, since the QuinLED boards share the same pinout, it will work with the WeMos D1 Mini ESP32 as well. 

Unfortunately, the Ethernet module of the QuinLED board requires many of the same pins as your PCB layout, and the serial ports, i2c, and the button will need to be moved. 

I2C: GPIO21 -> GPIO13 and GPIO22 -> GPIO14
PMS7003 Serial: GPIO1 -> GPIO15
MH-Z19 Serial: GPIO18 -> GPIO1 and GPIO19 -> GPIO3
Button: GPIO23 -> GPIO32
PMS7003_SET: GPIO26 -> GPIO33

**Questions**
- Do you see an issue with using the pins above? I've tried to avoid input only as well as bootstrap pins.
- In the readme, you also mention changing the pin of one of the dust sensors. Can you provide more info?

**Comment by nkitanov** [comment]
Hi,

In order to move the pins a new PCB is needed. I was planning to do that if I redisign th PCB (at least to free the serial port as it's now shared with MH sensor - the reason is that this PCB was initially designed for ESP8266) but never done this and currently I do not plan any changes to this PCB. Eventually if I find time I may rediesign completely new board but it will be with integrated esp32. But for this board there will be no change. I published kicad files, so you can try to redesign yourself for your needs.

Best regards
Nikolay
